### ISSUE TITLE
Conflicting Implementations in dependencies

### ISSUE THREAD

**Issue by lecoqjacob** [sarkahn/bevy_ascii_terminal#4]
<img width="739" alt="CleanShot 2022-07-07 at 19 13 06@2x" src="https://user-images.githubusercontent.com/9278174/177891562-f1dc0aab-b672-4a49-83b4-190c734dcc33.png">

Seems sarks grid is conflicting with the internal application of `Terminal` My intellisense cant really figure out what is happening

**Comment by sarkahn** [comment]
It's possible that is a false positive caused by another error - when/how did you see this pop up? What is the very first error listed in your log?

**Comment by lecoqjacob** [comment]
I believe rust analyzer is completely borked in the lat at release. I will close for now and open if it's still an issue
