### ISSUE TITLE
Tile to World Coordinates (and Camera)

### ISSUE THREAD

**Issue by matthemsteger** [sarkahn/bevy_ascii_terminal#5]
I am wondering how to get the world coordinates for the center of a tile? I believe default a single tile is a single world unit, so I thought it would just be a matter of setting the translation of the terminal to something (0,0) and then counting based on wherever that was (I assumed it would be the bottom left corner .. but expected it to be some corner). It doesnt seem to be the case. If I set it to (0,0), the center of my terminal is somewhere off-center.

How do you translate tile coordinates to world coordinates? An API would be wonderful and would also ease mouse pointing logic.

I was also trying to apply the same kind of thing for the camera (moving the camera along with the player) but also needed to translate tile coordinates to world coordinates.

The same if, perhaps, sprites were added on top of a terminal.

**Comment by sarkahn** [comment]
By default the center of the terminal is the pivot point. This complicates it a bit as the positions/centers of tiles will be offset by 0.5 depending on the size of your terminal. So for a 2x2 terminal the origin of the terminal sits at the position (bottom left corner) of tile [1,1]. For a 3x3 terminal the origin sits at the *center* of tile [1,1].

I can definitely set up some functions to translate world positions though, seems sensible. They should be in the next version which should be on crates.io shortly after bevy 0.8 releases.

**Comment by sarkahn** [comment]
Fixed by 47c01140bccbd0eac5b8626397d1ab64b6d23dd6
