### ISSUE TITLE
Multiple terminals with pixel scaling and different fonts severely missized in 0.12

### ISSUE THREAD

**Issue by Illiux** [sarkahn/bevy_ascii_terminal#9]
After updating from bevy 0.6->0.9, and bevy_ascii_terminal along with it, something has gone very wrong with my terminals:

![2022-12-26-091046_1600x896_scrot](https://user-images.githubusercontent.com/451390/209570599-1b293a54-dbae-4d6d-965a-53693f7882a3.png)
This is how it is supposed to look.

![2022-12-26-091005_1600x896_scrot](https://user-images.githubusercontent.com/451390/209570618-638db899-1c94-4142-aed9-5db8a7861057.png)
This is what it looks like after updating.

It seems almost as if everything is being rendered with 8x8 tiles when one terminal is using 16x16 tiles and the other 8x16.

**Comment by Illiux** [comment]
After noticing that this was in fact rendering with different _fonts_ than I intended, I dug a little and figured out what was happening. I directly set `TerminalMaterial` as I'm spawning my terminals, but now with `TerminalFont` being on them it gets immediately processed and my material is overridden. It works if I remove the `TerminalFont` component as I'm spawning the terminals, but this feels pretty awkward.

**Comment by sarkahn** [comment]
As discussed on discord the method for changing fonts will be changed in the next version, I will aim for something that fits in more naturally with how bevy handles textures/materials
